spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hanghe?serverTimezone=Asia/Seoul
    username: myuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20         # default: 10
      maximum-pool-size: 20    # default: 10
      connection-timeout: 3000 # default: 30000(30s)
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6380
